FORMAT: 1A
HOST: https://example.soukdesigner.com

# Soukdesigner - API

Souk is the Soukdesigner API allowing customers to integrate their soukdesigner store with any external system like ERP or Stock and Accounting management systems.

## Authentication

Get your API key for the authentication header token `X-Souk-Token` from your Soukdesigner Admin Panel.

# Group Taxonomies and Taxons

# /api/taxonomies

### List All Taxons [GET]

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>

+ Response 200 (application/json)

    + Body

              {
                 "count":2,
                 "current_page":1,
                 "pages":1,
                 "taxonomies":[
                    {
                       "id":1,
                       "name":"Categories",
                       "root":{
                          "id":1,
                          "name":"Categories",
                          "pretty_name":"Categories",
                          "permalink":"categories",
                          "parent_id":null,
                          "taxonomy_id":1,
                          "taxons":[
                             {
                                "id":3,
                                "name":"Watches",
                                "pretty_name":"Categories -\u003e Watches",
                                "permalink":"categories/watches",
                                "parent_id":1,
                                "taxonomy_id":1
                             },
                             {
                                "id":4,
                                "name":"Toys",
                                "pretty_name":"Categories -\u003e Toys",
                                "permalink":"categories/toys",
                                "parent_id":1,
                                "taxonomy_id":1
                             },
                             {
                                "id":5,
                                "name":"Perfumes",
                                "pretty_name":"Categories -\u003e Perfumes",
                                "permalink":"categories/perfumes",
                                "parent_id":1,
                                "taxonomy_id":1
                             }
                          ]
                       }
                    },
                    {
                       "id":2,
                       "name":"Brand",
                       "root":{
                          "id":2,
                          "name":"Brand",
                          "pretty_name":"Brand",
                          "permalink":"brand",
                          "parent_id":null,
                          "taxonomy_id":2,
                          "taxons":[
                             {
                                "id":6,
                                "name":"Happy Kids",
                                "pretty_name":"Brand -\u003e Happy Kids",
                                "permalink":"brand/happy-kids",
                                "parent_id":2,
                                "taxonomy_id":2
                             },
                             {
                                "id":7,
                                "name":"Prism Hour",
                                "pretty_name":"Brand -\u003e Prism Hour",
                                "permalink":"brand/prism-hour",
                                "parent_id":2,
                                "taxonomy_id":2
                             },
                             {
                                "id":8,
                                "name":"Smells like",
                                "pretty_name":"Brand -\u003e Smells like",
                                "permalink":"brand/smells-like",
                                "parent_id":2,
                                "taxonomy_id":2
                             }
                          ]
                       }
                    }
                 ]
              }
    
### Create a New Taxonomy [POST]

You may create your own Taxonomy using this action. It takes a JSON object containing a taxonomy section.

+ Request (application/json)

      {
         "taxonomy": {
           "name": "Country"
         }
      }

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>

+ Response 201 (application/json)

    + Headers

    + Body

              {
                 "id":3,
                 "name":"Country",
                 "root":{
                    "id":9,
                    "name":"Country",
                    "pretty_name":"Country",
                    "permalink":"country",
                    "parent_id":null,
                    "taxonomy_id":3,
                    "taxons":[

                    ]
                 }
              }    

# /api/taxonomies/{taxonomy_id}

### Show a taxonomy [GET]

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Body

            {
              "id":1,
              "name":"Categories",
              "root":{
                "id":1,
                "name":"Categories",
                "pretty_name":"Categories",
                "permalink":"categories",
                "parent_id":null,
                "taxonomy_id":1,
                "taxons":[
                  {
                    "id":3,
                    "name":"Watches",
                    "pretty_name":"Categories -\u003e Watches",
                    "permalink":"categories/watches",
                    "parent_id":1,
                    "taxonomy_id":1
                  },
                  {
                    "id":4,
                    "name":"Toys",
                    "pretty_name":"Categories -\u003e Toys",
                    "permalink":"categories/toys",
                    "parent_id":1,
                    "taxonomy_id":1
                  },
                  {
                    "id":5,
                    "name":"Perfumes",
                    "pretty_name":"Categories -\u003e Perfumes",
                    "permalink":"categories/perfumes",
                    "parent_id":1,
                    "taxonomy_id":1
                  }
                ]
              }
            }

### Update a Taxonomy [PUT]

For instance, to update a taxonomy's name, make this request:

`PUT /api/taxonomies/1?taxonomy[name]=Pants`

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Headers

    + Body

# /api/taxonomy/{taxonomy_id}/taxons

### List All Taxons under a specific Taxonomy

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Body

              {
                 "count":3,
                 "total_count":3,
                 "current_page":1,
                 "per_page":25,
                 "pages":1,
                 "taxons":[
                    {
                       "taxons":[

                       ],
                       "id":3,
                       "name":"Watches",
                       "pretty_name":"Categories -\u003e Watches",
                       "permalink":"categories/watches",
                       "parent_id":1,
                       "taxonomy_id":1
                    },
                    {
                       "taxons":[

                       ],
                       "id":4,
                       "name":"Toys",
                       "pretty_name":"Categories -\u003e Toys",
                       "permalink":"categories/toys",
                       "parent_id":1,
                       "taxonomy_id":1
                    },
                    {
                       "taxons":[

                       ],
                       "id":5,
                       "name":"Perfumes",
                       "pretty_name":"Categories -\u003e Perfumes",
                       "permalink":"categories/perfumes",
                       "parent_id":1,
                       "taxonomy_id":1
                    }
                 ]
              }

### Create a new Taxon under a specific taxonomy

+ Request (application/json)

        {
          "name": "Sapatos Furados",
          "permalink": "categories/sapatos-furados"
        }

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>

+ Response 201 (application/json)

    + Body

            {
               "id":9,
               "name":"Sapatos Furados",
               "pretty_name":"Categories -\u003e Sapatos Furados",
               "permalink":"categories/sapatos-furados",
               "parent_id":1,
               "taxonomy_id":1,
               "taxons":[

               ]
            }

# Group Products

# /api/products

### List All Products [GET]

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Body
    
            {
               "count":23,
               "total_count":23,
               "current_page":1,
               "per_page":25,
               "pages":1,
               "products":[
                  {
                     "id":7,
                     "name":"Sunny Doug",
                     "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
                     "price":"19.99",
                     "display_price":"$19.99",
                     "available_on":"2015-12-01T22:53:05.313Z",
                     "slug":"sunny-doug",
                     "meta_description":null,
                     "meta_keywords":null,
                     "shipping_category_id":1,
                     "taxon_ids":[
                        6,
                        4
                     ],
                     "total_on_hand":10,
                     "has_variants":false,
                     "master":{
                        "id":7,
                        "name":"Sunny Doug",
                        "sku":"",
                        "price":"19.99",
                        "weight":"0.0",
                        "height":null,
                        "width":null,
                        "depth":null,
                        "is_master":true,
                        "slug":"sunny-doug",
                        "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
                        "track_inventory":true,
                        "cost_price":null,
                        "display_price":"$19.99",
                        "options_text":"",
                        "in_stock":true,
                        "is_backorderable":false,
                        "total_on_hand":10,
                        "is_destroyed":false,
                        "option_values":[
            
                        ],
                        "images":[
                           {
                              "id":22,
                              "position":1,
                              "attachment_content_type":"image/jpeg",
                              "attachment_file_name":"sunny_doug.jpg",
                              "type":"Spree::Image",
                              "attachment_updated_at":"2015-12-01T22:53:33.172Z",
                              "attachment_width":500,
                              "attachment_height":500,
                              "alt":null,
                              "viewable_type":"Spree::Variant",
                              "viewable_id":7,
                              "mini_url":"https://s3.amazonaws.com/media.soukdesigner.com/dude/image/22/mini/sunny_doug.jpg?1449010413",
                              "small_url":"https://s3.amazonaws.com/media.soukdesigner.com/dude/image/22/small/sunny_doug.jpg?1449010413",
                              "product_url":"https://s3.amazonaws.com/media.soukdesigner.com/dude/image/22/product/sunny_doug.jpg?1449010413",
                              "large_url":"https://s3.amazonaws.com/media.soukdesigner.com/dude/image/22/large/sunny_doug.jpg?1449010413"
                           }
                        ]
                     },
                     "variants":[
            
                     ],
                     "option_types":[
            
                     ],
                     "product_properties":[
                        {
                           "id":20,
                           "product_id":7,
                           "property_id":6,
                           "value":"Medium class",
                           "property_name":"Type"
                        },
                        {
                           "id":21,
                           "product_id":7,
                           "property_id":7,
                           "value":"6.75\" tall, 3.75\" dia. base, 3\" dia. rim",
                           "property_name":"Size"
                        }
                     ],
                     "classifications":[
                        {
                           "taxon_id":4,
                           "position":2,
                           "taxon":{
                              "id":4,
                              "name":"Toys",
                              "pretty_name":"Categories -\u003e Toys",
                              "permalink":"categories/toys",
                              "parent_id":1,
                              "taxonomy_id":1,
                              "taxons":[
            
                              ]
                           }
                        },
                        {
                           "taxon_id":6,
                           "position":1,
                           "taxon":{
                              "id":6,
                              "name":"Happy Kids",
                              "pretty_name":"Brand -\u003e Happy Kids",
                              "permalink":"brand/happy-kids",
                              "parent_id":2,
                              "taxonomy_id":2,
                              "taxons":[
            
                              ]
                           }
                        }
                     ]
                  },
                  {
                     "id":22,
                     "name":"Lion Bar",
                     "description":"Lion King",
                     "price":"60.0",
                     "display_price":"$60.00",
                     "available_on":"2014-08-10T00:00:00.000Z",
                     "slug":"lion-bar",
                     "meta_description":null,
                     "meta_keywords":null,
                     "shipping_category_id":1,
                     "taxon_ids":[
                        14
                     ],
                     "total_on_hand":5,
                     "has_variants":false,
                     "master":{
                        "id":32,
                        "name":"Lion Bar",
                        "sku":"sku0007",
                        "price":"60.0",
                        "weight":"0.0",
                        "height":null,
                        "width":null,
                        "depth":null,
                        "is_master":true,
                        "slug":"lion-bar",
                        "description":"Lion King",
                        "track_inventory":true,
                        "cost_price":null,
                        "display_price":"$60.00",
                        "options_text":"",
                        "in_stock":false,
                        "is_backorderable":false,
                        "total_on_hand":5,
                        "is_destroyed":false,
                        "option_values":[
            
                        ],
                        "images":[
            
                        ]
                     },
                     "variants":[
            
                     ],
                     "option_types":[
            
                     ],
                     "product_properties":[
            
                     ],
                     "classifications":[
                        {
                           "taxon_id":14,
                           "position":2,
                           "taxon":{
                              "id":14,
                              "name":"chocolate",
                              "pretty_name":"min-market -\u003e chocolate",
                              "permalink":"min-market/chocolate",
                              "parent_id":9,
                              "taxonomy_id":3,
                              "taxons":[
            
                              ]
                           }
                        }
                     ]
                  },
                  {
                     "id":23,
                     "name":"Concha y Toro",
                     "description":null,
                     "price":"600.0",
                     "display_price":"$600.00",
                     "available_on":"2014-08-10T00:00:00.000Z",
                     "slug":"concha-y-toro",
                     "meta_description":null,
                     "meta_keywords":null,
                     "shipping_category_id":1,
                     "taxon_ids":[
                        13
                     ],
                     "total_on_hand":6,
                     "has_variants":false,
                     "master":{
                        "id":33,
                        "name":"Concha y Toro",
                        "sku":"sku0008",
                        "price":"600.0",
                        "weight":"0.0",
                        "height":null,
                        "width":null,
                        "depth":null,
                        "is_master":true,
                        "slug":"concha-y-toro",
                        "description":null,
                        "track_inventory":true,
                        "cost_price":null,
                        "display_price":"$600.00",
                        "options_text":"",
                        "in_stock":true,
                        "is_backorderable":false,
                        "total_on_hand":6,
                        "is_destroyed":false,
                        "option_values":[
            
                        ],
                        "images":[
            
                        ]
                     },
                     "variants":[
            
                     ],
                     "option_types":[
            
                     ],
                     "product_properties":[
            
                     ],
                     "classifications":[
                        {
                           "taxon_id":13,
                           "position":3,
                           "taxon":{
                              "id":13,
                              "name":"wine",
                              "pretty_name":"min-market -\u003e wine",
                              "permalink":"min-market/wine",
                              "parent_id":9,
                              "taxonomy_id":3,
                              "taxons":[
            
                              ]
                           }
                        }
                     ]
                  }
               ]
            }

### Create a New Product [POST]

You may create your own products using this action. It takes a JSON object containing a product section.

+ Request (application/json)

            {
               "product": {
                  "name":"Nosi bummer",
                  "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
                  "price":"19.99",
                  "display_price":"$19.99",
                  "slug":"sunny-doug",
                  "total_on_hand":10,
                  "shipping_category_id":1,
                  "master":{
                     "name":"Total Bummer",
                     "sku":"stck-1923",
                     "price":"19.99",
                     "weight":"0.2",
                     "height":null,
                     "width":null,
                     "depth":null,
                     "slug":"sunny-doug",
                     "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
                     "track_inventory":true,
                     "cost_price":null,
                     "display_price":"$19.99",
                     "total_on_hand":10
                  }
               }
            }
    
    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
        
+ Response 201 (application/json)

    + Headers

    + Body
    
            {
               "id":18,
               "name":"Nosi bummer",
               "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
               "price":"19.99",
               "display_price":"$19.99",
               "available_on":"2016-02-09T21:58:28.668Z",
               "slug":"nosi-bummer-1896e419-8529-4c24-9338-33b576fb2dc1",
               "meta_description":null,
               "meta_keywords":null,
               "shipping_category_id":1,
               "taxon_ids":[
            
               ],
               "total_on_hand":0,
               "has_variants":false,
               "master":{
                  "id":28,
                  "name":"Nosi bummer",
                  "sku":"",
                  "price":"19.99",
                  "weight":"0.0",
                  "height":null,
                  "width":null,
                  "depth":null,
                  "is_master":true,
                  "slug":"nosi-bummer-1896e419-8529-4c24-9338-33b576fb2dc1",
                  "description":"Nobis exercitationem voluptatibus modi occaecati consequuntur vel ipsa amet. Maiores optio officia aut est sed tempore ex. Ut non quisquam aspernatur minima amet. Recusandae officiis laboriosam natus qui ad soluta molestiae dicta.",
                  "track_inventory":true,
                  "cost_price":null,
                  "display_price":"$19.99",
                  "options_text":"",
                  "in_stock":false,
                  "is_backorderable":false,
                  "total_on_hand":0,
                  "is_destroyed":false,
                  "option_values":[
            
                  ],
                  "images":[
            
                  ]
               },
               "variants":[
            
               ],
               "option_types":[
            
               ],
               "product_properties":[
            
               ],
               "classifications":[
            
               ]
            }

# /api/products/{product_id}

A slugged `product_name` can be used instead of `product_id`

### Show a Product [GET]

+ Request (application/json)

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Body
    
            {
               "id":12,
               "name":"212 Men Carolina Herrera",
               "description":"Sed totam accusantium veniam illum dolorem quam. Blanditiis id voluptates ut quam eum voluptate. Eos dolore delectus voluptas et repellendus vitae commodi deserunt. Rerum rerum sed voluptatem sed rerum quae similique eos.",
               "price":"82.99",
               "display_price":"$82.99",
               "available_on":"2016-02-05T19:49:38.763Z",
               "slug":"212-men-carolina-herrera",
               "meta_description":null,
               "meta_keywords":null,
               "shipping_category_id":1,
               "taxon_ids":[
                  5,
                  8
               ],
               "total_on_hand":10,
               "has_variants":false,
               "master":{
                  "id":12,
                  "name":"212 Men Carolina Herrera",
                  "sku":"",
                  "price":"82.99",
                  "weight":"0.0",
                  "height":null,
                  "width":null,
                  "depth":null,
                  "is_master":true,
                  "slug":"212-men-carolina-herrera",
                  "description":"Sed totam accusantium veniam illum dolorem quam. Blanditiis id voluptates ut quam eum voluptate. Eos dolore delectus voluptas et repellendus vitae commodi deserunt. Rerum rerum sed voluptatem sed rerum quae similique eos.",
                  "track_inventory":true,
                  "cost_price":null,
                  "display_price":"$82.99",
                  "options_text":"",
                  "in_stock":true,
                  "is_backorderable":false,
                  "total_on_hand":10,
                  "is_destroyed":false,
                  "option_values":[
            
                  ],
                  "images":[
                     {
                        "id":27,
                        "position":1,
                        "attachment_content_type":"image/jpeg",
                        "attachment_file_name":"212.jpg",
                        "type":"Spree::Image",
                        "attachment_updated_at":"2016-02-05T19:49:50.133Z",
                        "attachment_width":500,
                        "attachment_height":500,
                        "alt":null,
                        "viewable_type":"Spree::Variant",
                        "viewable_id":12,
                        "mini_url":"/spree/products/store1/27/mini/212.jpg?1454701790",
                        "small_url":"/spree/products/store1/27/small/212.jpg?1454701790",
                        "product_url":"/spree/products/store1/27/product/212.jpg?1454701790",
                        "large_url":"/spree/products/store1/27/large/212.jpg?1454701790"
                     }
                  ]
               },
               "variants":[
            
               ],
               "option_types":[
            
               ],
               "product_properties":[
                  {
                     "id":30,
                     "product_id":12,
                     "property_id":1,
                     "value":"Perfume X",
                     "property_name":"Manufacturer"
                  },
                  {
                     "id":31,
                     "product_id":12,
                     "property_id":2,
                     "value":"Fragrance Yes",
                     "property_name":"Brand"
                  },
                  {
                     "id":32,
                     "product_id":12,
                     "property_id":3,
                     "value":"CH1002",
                     "property_name":"Model"
                  },
                  {
                     "id":33,
                     "product_id":12,
                     "property_id":9,
                     "value":"Men's",
                     "property_name":"Gender"
                  }
               ],
               "classifications":[
                  {
                     "taxon_id":5,
                     "position":1,
                     "taxon":{
                        "id":5,
                        "name":"Perfumes",
                        "pretty_name":"Categories -\u003e Perfumes",
                        "permalink":"categories/perfumes",
                        "parent_id":1,
                        "taxonomy_id":1,
                        "taxons":[
            
                        ]
                     }
                  },
                  {
                     "taxon_id":8,
                     "position":1,
                     "taxon":{
                        "id":8,
                        "name":"Smells like",
                        "pretty_name":"Brand -\u003e Smells like",
                        "permalink":"brand/smells-like",
                        "parent_id":2,
                        "taxonomy_id":2,
                        "taxons":[
            
                        ]
                     }
                  }
               ]
            }

### Update a Product [PUT]

You any update any field of a created product. A slugged `product_name` can be used instead of `product_id`

+ Request (application/json)

            {
               "product": {
                  "description":"This is my updated product description",
                  "price":"29.99",
                  "display_price":"$29.99"
               }
            }

    + Headers
    
            X-Souk-Token: <your-api-key-from-souk-admin-panel>
            
+ Response 200 (application/json)

    + Headers

    + Body
    
            {
               "id":17,
               "name":"Nosi bummer",
               "description":"This is my updated product description",
               "price":"29.99",
               "display_price":"$29.99",
               "available_on":"2016-02-09T21:45:09.049Z",
               "slug":"nosi-bummer",
               "meta_description":null,
               "meta_keywords":null,
               "shipping_category_id":1,
               "taxon_ids":[
            
               ],
               "total_on_hand":0,
               "has_variants":false,
               "master":{
                  "id":27,
                  "name":"Nosi bummer",
                  "sku":"",
                  "price":"29.99",
                  "weight":"0.0",
                  "height":null,
                  "width":null,
                  "depth":null,
                  "is_master":true,
                  "slug":"nosi-bummer",
                  "description":"This is my updated product description",
                  "track_inventory":true,
                  "cost_price":null,
                  "display_price":"$29.99",
                  "options_text":"",
                  "in_stock":false,
                  "is_backorderable":false,
                  "total_on_hand":0,
                  "is_destroyed":false,
                  "option_values":[
            
                  ],
                  "images":[
            
                  ]
               },
               "variants":[
            
               ],
               "option_types":[
            
               ],
               "product_properties":[
            
               ],
               "classifications":[
            
               ]
            }
